### ISSUE TITLE
System.Web.Http

### ISSUE THREAD

**Issue by sergiofagostinho** [dennisroche/TopShelf.Owin#1]
Hi,

Following your sample, when I try to run a simple service, I get the following exception on the OwinEndpoint line:
> Could not load file or assembly 'System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Which dependency am I missing?

**Comment by sergiofagostinho** [comment]
Ok, got it:
* Microsoft.AspNet.WebApi.Client
* Microsoft.AspNet.WebApi.Core
* Microsoft.AspNet.WebApi.Owin

Maybe this should be in the .nuspec file?

**Comment by dennisroche** [comment]
@sergiofagostinho I only just saw this issue. I'll build a simple service and check if I need to update the dependencies. Feel free to open a PR, I have added AppVeyor CI this morning so it is easy to build and publish a new nuget package.

**Comment by dennisroche** [comment]
@sergiofagostinho I finally got around to do this. Thanks for the original issue.
