### ISSUE TITLE
Autofac Dependancy Injection not working

### ISSUE THREAD

**Issue by Kushal5** [dennisroche/TopShelf.Owin#19]
I am not able to get Injection up with this project. Controllers are always using parameterless constructor.

        HostFactory.Run(c =>
        {
            c.RunAsNetworkService();

            c.Service<YourService>(s =>
            {
                s.ConstructUsing(() => new YourService());
                s.WhenStarted((service, control) => service.Start());
                s.WhenStopped((service, control) => service.Stop());

                s.OwinEndpoint(app =>
                {
                    app.Domain = "localhost";
                    app.Port = 8080;

                });

                // Create your container
                var builder = new ContainerBuilder();
                builder.RegisterType<SampleDependency>().As<ISampleDependency>().SingleInstance().PropertiesAutowired();
                builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
                var container = builder.Build();
                
                s.OwinEndpoint(app =>
                {
                    app.UseDependencyResolver(new AutofacWebApiDependencyResolver(container));
                });

            });

        });

**Comment by Kushal5** [comment]
It should be as:

```
                    //Autofac container setup here
                    s.OwinEndpoint(app =>
                    {
                        app.Domain = "localhost";
                        app.Port = 8080;
                        app.UseDependencyResolver(new AutofacWebApiDependencyResolver(container));
                    });
```

**Comment by dennisroche** [comment]
The `OwinEndpoint` is only declared once; I've updated the README. Let me know if that's clearer.
