### ISSUE TITLE
Service doesn't work on lan

### ISSUE THREAD

**Issue by Rajivhost** [dennisroche/TopShelf.Owin#6]
Hi,
I can't reach my service over the network.
This is my configuration:
![image](https://cloud.githubusercontent.com/assets/3539984/13427317/7d42633a-dfb3-11e5-9d2c-9a32a81b37ff.png)

**Comment by dennisroche** [comment]
More likely an issue with your networking, e.g. a firewall blocking the port, than with the library itself. You can confirm this by **temporarily** disabling Windows Firewall.
